name: CI

on:
  push:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config Release

    - name: Upload Artifact
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Infinite_matrix.${{ github.run_number }}-Linux.deb
          asset_name: Infinite_matrix.${{ github.run_number }}-Linux.deb
          asset_content_type: application/vnd.debian.binary-package
